version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=eShop-super-secret-key-change-in-production
      # Add your OpenAI API key here if using the chatbot
      - OPENAI_API_KEY=
    volumes:
      # Persist the database - using named volume for Windows compatibility
      - db-data:/app/ecommerce.db
    restart: unless-stopped
    networks:
      - ecommerce-network

  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ecommerce-network

volumes:
  db-data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge 